import { FormEvent, KeyboardEvent, ReactNode, useEffect, useMemo, useRef, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";

import { useAuth } from "../auth/useAuth";
import { listRegistrationClients, type RegistrationClient } from "../registration/registrationClientApi";
import { listRegistrationFacilities, type RegistrationFacility } from "../registration/registrationFacilityApi";
import { listRegistrationPersonnel, type RegistrationPersonnel } from "../registration/registrationPersonnelApi";
import { Button } from "../ui/components/Button";
import { RecordAccordion } from "../ui/components/RecordAccordion";
import { WorkflowContentCard, WorkflowModal } from "../ui/components/WorkflowModal";
import { WorkspaceShell } from "../ui/components/WorkspaceShell";
import { appointmentProfiles, appointmentScopes, createAuditorAppointment, listAuditorAppointments, type AppointmentProfile, type AppointmentScope } from "./auditorAppointmentsApi";

const steps = [{ key: "auditor", label: "Auditor" }, { key: "authority", label: "Authority" }, { key: "scope", label: "Scope" }, { key: "review", label: "Review" }];
const bases = ["LEAD_GUARDIAN", "DEDICATED_AUDITOR", "QUALITY_ASSURANCE", "EXPLICIT_ASSIGNMENT", "OGI_ENTERPRISE_APPOINTMENT"] as const;
const profileLabels: Record<AppointmentProfile, string> = { AUDIT_TEAM_MEMBER: "Audit team member", AUDIT_OPERATOR: "Audit operator", LEAD_AUDITOR: "Lead auditor", AUDIT_REVIEWER: "Audit reviewer", AUDIT_APPROVER: "Audit approver", FULL_AUDIT_AUTHORITY: "Full audit authority" };

interface FormState { personnelId:string; profile:AppointmentProfile; basis:string; scope:AppointmentScope; clientId:string; facilityIds:string[]; validFrom:string; validUntil:string; reason:string }
const emptyForm = (): FormState => ({ personnelId:"", profile:"AUDIT_OPERATOR", basis:"EXPLICIT_ASSIGNMENT", scope:"FACILITY_SPECIFIC", clientId:"", facilityIds:[], validFrom:new Date().toISOString().slice(0,10), validUntil:"", reason:"" });

export function AuditorAppointmentsPage() {
  const auth = useAuth(); const queryClient = useQueryClient();
  const canManage = auth.canUsePermission("manage_audit_appointment");
  const [statusFilter,setStatusFilter]=useState(""); const [search,setSearch]=useState(""); const [expanded,setExpanded]=useState<string|null>(null); const [open,setOpen]=useState(false); const [step,setStep]=useState(0); const [form,setForm]=useState<FormState>(emptyForm); const [message,setMessage]=useState<string|null>(null);
  const appointmentsQuery=useQuery({queryKey:["auditor-appointments"],queryFn:listAuditorAppointments,retry:false});
  const clientsQuery=useQuery({queryKey:["registration-clients","appointments"],queryFn:listRegistrationClients,retry:false});
  const personnelQuery=useQuery({queryKey:["registration-personnel","appointments"],queryFn:()=>listRegistrationPersonnel({status:"ACTIVE"}),retry:false});
  const facilitiesQuery=useQuery({queryKey:["registration-facilities","appointments",form.clientId],queryFn:()=>listRegistrationFacilities(form.clientId?{clientId:form.clientId}:{}),enabled:form.scope==="FACILITY_SPECIFIC"&&Boolean(form.clientId),retry:false});
  const filtered=useMemo(()=> (appointmentsQuery.data?.appointments??[]).filter(a=>(!statusFilter||a.status===statusFilter)&&(!search||`${a.full_name} ${a.business_identifier} ${a.audit_number??""} ${a.profile}`.toLowerCase().includes(search.toLowerCase()))),[appointmentsQuery.data,statusFilter,search]);
  const createMutation=useMutation({mutationFn:createAuditorAppointment,onSuccess:(result)=>{setOpen(false);setMessage(`${result.identifier} created for audit ${result.audit_number} with ${friendly(result.status)} status.`);void queryClient.invalidateQueries({queryKey:["auditor-appointments"]});},onError:()=>setMessage("The appointment could not be created. Confirm the migration and your authority, then try again.")});
  function begin(){setForm(emptyForm());setStep(0);setMessage(null);setOpen(true)}
  function submit(event:FormEvent){event.preventDefault();if(step<3){setStep(v=>v+1);return}createMutation.mutate({personnel_id:form.personnelId,profile:form.profile,authority_basis:form.basis,scope_mode:form.scope,...(form.scope!=="OGI_ENTERPRISE"?{client_id:form.clientId}:{}),facility_ids:form.scope==="FACILITY_SPECIFIC"?form.facilityIds:[],valid_from:form.validFrom,...(form.validUntil?{valid_until:form.validUntil}:{}),reason:form.reason})}
  return <WorkspaceShell title="Auditor Appointments" description="Appoint qualified personnel to perform, lead, review, or approve facility audits within a governed scope." headingId="auditor-appointments" navigation={null} sectionTitle="" sectionDescription="" showSectionHeader={false} headerActions={canManage?<Button onClick={begin}>New Appointment</Button>:null}>
    <div className="space-y-5">
      <section className="rounded-panel border border-border bg-white p-5 shadow-sm"><div className="grid gap-4 md:grid-cols-[1fr_15rem]"><label className="font-semibold">Find an appointment<input className="mt-2 w-full rounded-component border border-border px-3 py-3 font-normal" onChange={e=>setSearch(e.target.value)} placeholder="Name, appointment number, or authority" value={search}/></label><label className="font-semibold">Status<select className="mt-2 w-full rounded-component border border-border px-3 py-3 font-normal" onChange={e=>setStatusFilter(e.target.value)} value={statusFilter}><option value="">All statuses</option>{["PENDING","ACTIVE","SUSPENDED","REVOKED","EXPIRED"].map(v=><option key={v}>{v}</option>)}</select></label></div></section>
      {message?<p className="rounded-component border border-primary-blue/30 bg-blue-50 px-4 py-3 text-sm font-semibold text-primary-navy" role="status">{message}</p>:null}
      {appointmentsQuery.isLoading?<p role="status">Loading auditor appointments.</p>:appointmentsQuery.isError?<Unavailable/>:filtered.length===0?<p className="rounded-panel border border-border bg-white p-8 text-center text-text-muted">No auditor appointments match the current filters.</p>:<div className="space-y-3">{filtered.map(a=><RecordAccordion id={`appointment-${a.id}`} expanded={expanded===a.id} onToggle={()=>setExpanded(expanded===a.id?null:a.id)} key={a.id} summary={<div className="grid items-center gap-3 md:grid-cols-[1.4fr_1fr_auto]"><div><p className="text-xs font-bold uppercase tracking-wide text-primary-blue">{a.business_identifier}</p><h2 className="mt-1 text-lg font-semibold text-primary-navy">{a.full_name}</h2><p className="text-sm text-text-muted">{profileLabels[a.profile]}</p></div><div><p className="text-sm font-semibold">{friendly(a.scope_mode)}</p><p className="text-sm text-text-muted">Effective {dateLabel(a.valid_from)}</p></div><Status value={a.status}/></div>}><div className="grid gap-4 rounded-panel border border-border bg-elevated p-5 sm:grid-cols-2 lg:grid-cols-5"><Fact label="Audit number" value={a.audit_number??"Historical appointment"}/><Fact label="Authority basis" value={friendly(a.authority_basis)}/><Fact label="Capabilities" value={a.capabilities.map(friendly).join(", ")}/><Fact label="Valid through" value={a.valid_until?dateLabel(a.valid_until):"No scheduled end"}/><Fact label="Affiliation" value={friendly(a.organizational_affiliation)}/></div></RecordAccordion>)}</div>}
    </div>
    {open?<AppointmentOverlay form={form} setForm={setForm} step={step} setStep={setStep} onClose={()=>setOpen(false)} onSubmit={submit} personnel={personnelQuery.data?.personnel??[]} clients={clientsQuery.data?.clients??[]} facilities={facilitiesQuery.data?.facilities??[]} pending={createMutation.isPending}/>:null}
  </WorkspaceShell>
}

function AppointmentOverlay({form,setForm,step,setStep,onClose,onSubmit,personnel,clients,facilities,pending}:{form:FormState;setForm:(f:FormState)=>void;step:number;setStep:(n:number)=>void;onClose:()=>void;onSubmit:(e:FormEvent)=>void;personnel:RegistrationPersonnel[];clients:RegistrationClient[];facilities:RegistrationFacility[];pending:boolean}) {
  const dialogRef=useRef<HTMLDivElement>(null); useEffect(()=>{dialogRef.current?.focus()},[]);
  function keys(e:KeyboardEvent<HTMLDivElement>){if(e.key==="Escape")onClose()}
  const selectedPerson=personnel.find(p=>p.id===form.personnelId); const selectedClient=clients.find(c=>c.id===form.clientId);
  const valid=step===0?Boolean(form.personnelId):step===1?Boolean(form.profile&&form.basis):step===2?Boolean(form.validFrom&&(form.scope==="OGI_ENTERPRISE"||(form.clientId&&(form.scope!=="FACILITY_SPECIFIC"||form.facilityIds.length)))):Boolean(form.reason.trim());
  return <WorkflowModal currentStep={step} dialogRef={dialogRef} eyebrow="Governance · Auditor authority" footer={<><Button variant="secondary" onClick={step===0?onClose:()=>setStep(step-1)}>{step===0?"Cancel":"Back"}</Button><Button disabled={!valid||pending} type="submit">{step===3?(pending?"Creating…":"Create Appointment"):"Continue"}</Button></>} onKeyDown={keys} onSubmit={onSubmit} steps={steps} title="New Auditor Appointment" titleId="new-auditor-appointment">
    <WorkflowContentCard currentLabel={steps[step].label} stepNumber={step+1} totalSteps={4}>
      {step===0?<Field label="Auditor"><select className="cl-form-control" value={form.personnelId} onChange={e=>setForm({...form,personnelId:e.target.value})} required><option value="">Select an auditor from active personnel</option>{personnel.map(p=><option key={p.id} value={p.id}>{p.full_name} · {friendly(p.organizational_affiliation??"CLIENT")}</option>)}</select><p className="cl-form-hint">Select the registered person who will receive governed audit authority.</p></Field>:null}
      {step===1?<div className="space-y-5"><Field label="Authority profile"><select className="cl-form-control" value={form.profile} onChange={e=>setForm({...form,profile:e.target.value as AppointmentProfile})}>{appointmentProfiles.map(p=><option key={p} value={p}>{profileLabels[p]}</option>)}</select></Field><Field label="Authority basis"><select className="cl-form-control" value={form.basis} onChange={e=>setForm({...form,basis:e.target.value})}>{bases.map(b=><option key={b} value={b}>{friendly(b)}</option>)}</select></Field></div>:null}
      {step===2?<div className="space-y-5"><Field label="Appointment scope"><select className="cl-form-control" value={form.scope} onChange={e=>setForm({...form,scope:e.target.value as AppointmentScope,clientId:"",facilityIds:[]})}>{appointmentScopes.map(s=><option key={s} value={s}>{friendly(s)}</option>)}</select></Field>{form.scope!=="OGI_ENTERPRISE"?<Field label="Client"><select className="cl-form-control" value={form.clientId} onChange={e=>setForm({...form,clientId:e.target.value,facilityIds:[]})}><option value="">Select client</option>{clients.filter(c=>c.status==="ACTIVE").map(c=><option key={c.id} value={c.id}>{c.organization_name}</option>)}</select></Field>:null}{form.scope==="FACILITY_SPECIFIC"&&form.clientId?<fieldset><legend className="font-semibold">Facilities</legend><div className="mt-2 grid gap-2 sm:grid-cols-2">{facilities.filter(f=>f.operational_status==="ACTIVE").map(f=><label className="rounded-component border border-border bg-white p-3" key={f.id}><input checked={form.facilityIds.includes(f.id)} className="mr-2" onChange={e=>setForm({...form,facilityIds:e.target.checked?[...form.facilityIds,f.id]:form.facilityIds.filter(id=>id!==f.id)})} type="checkbox"/>{f.facility_name}</label>)}</div></fieldset>:null}<div className="grid gap-4 sm:grid-cols-2"><Field label="Valid from"><input className="cl-form-control" type="date" value={form.validFrom} onChange={e=>setForm({...form,validFrom:e.target.value})}/></Field><Field label="Valid until (optional)"><input className="cl-form-control" type="date" value={form.validUntil} onChange={e=>setForm({...form,validUntil:e.target.value})}/></Field></div></div>:null}
      {step===3?<div className="space-y-5"><div className="grid gap-3 rounded-panel border border-border bg-elevated p-4 sm:grid-cols-2"><Fact label="Auditor" value={selectedPerson?.full_name??"—"}/><Fact label="Authority" value={profileLabels[form.profile]}/><Fact label="Basis" value={friendly(form.basis)}/><Fact label="Scope" value={form.scope==="OGI_ENTERPRISE"?"OGI enterprise":`${friendly(form.scope)} · ${selectedClient?.organization_name??"—"}`}/></div><Field label="Appointment reason"><textarea className="cl-form-control min-h-28" value={form.reason} onChange={e=>setForm({...form,reason:e.target.value})} placeholder="State why this authority is being granted or nominated."/></Field><p className="text-sm text-text-muted">OGI appointments become Active immediately. Client appointments may enter Pending status for OGI governance.</p></div>:null}
    </WorkflowContentCard>
  </WorkflowModal>
}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="block font-semibold text-primary-navy">{label}<div className="mt-2 font-normal">{children}</div></label>}
function Fact({label,value}:{label:string;value:string}){return <div><p className="text-xs font-bold uppercase tracking-wide text-primary-blue">{label}</p><p className="mt-1 text-sm font-medium text-primary-navy">{value}</p></div>}
function Status({value}:{value:string}){const tone=value==="ACTIVE"?"border-emerald-300 bg-emerald-50 text-emerald-800":value==="PENDING"?"border-amber-300 bg-amber-50 text-amber-800":"border-slate-300 bg-slate-50 text-slate-700";return <span className={`w-fit rounded-full border px-3 py-1 text-xs font-bold ${tone}`}>{friendly(value)}</span>}
function Unavailable(){return <div className="rounded-panel border border-amber-300 bg-amber-50 p-6"><h2 className="font-semibold text-primary-navy">Auditor Appointments is not available yet</h2><p className="mt-2 text-sm text-text-muted">The page is installed, but the current database or session does not yet expose the appointment service. Deploy the approved migration and refresh the session permissions.</p></div>}
function friendly(value:string){return value.toLowerCase().replaceAll("_"," ").replace(/(^|\s)\S/g,c=>c.toUpperCase())}
function dateLabel(value:string){const d=new Date(value.length===10?`${value}T00:00:00`:value);return Number.isNaN(d.valueOf())?value:new Intl.DateTimeFormat(undefined,{dateStyle:"medium"}).format(d)}
