import {type FormEvent,type ReactNode,useState} from "react";
import {useMutation} from "@tanstack/react-query";
import {isApiError} from "../api/errors";
import {Button} from "../ui/components/Button";
import {createIncident,incidentCategories,incidentSeverities,incidentTypes,type CreateIncidentRequest,type CreatedIncident} from "./incidentApi";

export function IncidentContextRegistration({facilityId,disabled,onCreated}:{readonly facilityId:string;readonly disabled:boolean;readonly onCreated:(incident:CreatedIncident)=>void}){
  const [open,setOpen]=useState(false);const [message,setMessage]=useState<string|null>(null);
  const [form,setForm]=useState({category:"INCIDENT_EVENT",type:"OTHER",severity:"LOW",occurredAt:"",location:"",persons:"0",description:"",actions:"",emergency:false,followUp:false});
  const mutation=useMutation({mutationFn:(request:CreateIncidentRequest)=>createIncident(request),onSuccess:(incident)=>{setMessage(`Incident ${incident.business_identifier} registered. It is now selected for verification.`);setOpen(false);onCreated(incident);},onError:(error)=>setMessage(isApiError(error)?error.message:"The Incident could not be registered.")});
  function submit(event:FormEvent){event.preventDefault();setMessage(null);const occurredAt=new Date(form.occurredAt);const persons=Number(form.persons);if(!form.occurredAt||Number.isNaN(occurredAt.valueOf())||!form.description.trim()||!Number.isInteger(persons)||persons<0){setMessage("A valid incident date, time, non-negative persons involved, and description are required.");return;}mutation.mutate({facility_id:facilityId,incident_category:form.category as CreateIncidentRequest["incident_category"],incident_type:form.type as CreateIncidentRequest["incident_type"],severity:form.severity as CreateIncidentRequest["severity"],incident_date:occurredAt.toISOString(),...(form.location.trim()?{incident_location:form.location.trim()}:{}),persons_involved:persons,description:form.description.trim(),...(form.actions.trim()?{actions_taken:form.actions.trim()}:{}),emergency_services_contacted:form.emergency,follow_up_required:form.followUp});}
  if(!open)return <div className="mt-3"><Button disabled={disabled||!facilityId} onClick={()=>{setOpen(true);setMessage(null);}} type="button" variant="secondary">Register New Incident</Button>{message?<p className="mt-2 text-sm text-teal-700" role="status">{message}</p>:null}</div>;
  return <form className="mt-4 rounded-component border border-blue-200 bg-white p-4" onSubmit={submit}>
    <h3 className="font-semibold text-primary-navy">Register Incident</h3><p className="mt-1 text-sm text-text-muted">The current Client and Facility are locked. The Incident Number and reporter are assigned by the governed registry.</p>
    <div className="mt-4 grid gap-4 md:grid-cols-2">
      <Select label="Incident category" value={form.category} values={incidentCategories} set={(category)=>setForm({...form,category})}/><Select label="Incident type" value={form.type} values={incidentTypes} set={(type)=>setForm({...form,type})}/><Select label="Severity" value={form.severity} values={incidentSeverities} set={(severity)=>setForm({...form,severity})}/>
      <Field label="Incident date and time"><input className={control} required type="datetime-local" value={form.occurredAt} onChange={(e)=>setForm({...form,occurredAt:e.currentTarget.value})}/></Field>
      <Field label="Location"><input className={control} maxLength={255} value={form.location} onChange={(e)=>setForm({...form,location:e.currentTarget.value})}/></Field><Field label="Persons involved"><input className={control} min="0" step="1" type="number" value={form.persons} onChange={(e)=>setForm({...form,persons:e.currentTarget.value})}/></Field>
      <Field label="Description"><textarea className={control} required rows={3} value={form.description} onChange={(e)=>setForm({...form,description:e.currentTarget.value})}/></Field><Field label="Actions taken"><textarea className={control} rows={3} value={form.actions} onChange={(e)=>setForm({...form,actions:e.currentTarget.value})}/></Field>
    </div><div className="mt-4 flex flex-wrap gap-4"><Check label="Emergency services contacted" checked={form.emergency} set={(emergency)=>setForm({...form,emergency})}/><Check label="Follow-up required" checked={form.followUp} set={(followUp)=>setForm({...form,followUp})}/></div>
    {message?<p className="mt-3 text-sm text-red-700" role="alert">{message}</p>:null}<div className="mt-4 flex gap-2"><Button disabled={mutation.isPending} type="submit">{mutation.isPending?"Registering…":"Register Incident"}</Button><Button disabled={mutation.isPending} onClick={()=>{setOpen(false);setMessage(null);}} type="button" variant="secondary">Cancel</Button></div>
  </form>;
}
const control="mt-2 min-h-10 w-full rounded-component border border-border bg-white px-3 py-2 text-sm";
function Field({label,children}:{label:string;children:ReactNode}){return <label className="text-sm font-semibold text-primary-navy">{label}{children}</label>}
function Select({label,value,values,set}:{label:string;value:string;values:readonly string[];set:(value:string)=>void}){return <Field label={label}><select className={control} value={value} onChange={(e)=>set(e.currentTarget.value)}>{values.map((item)=><option key={item} value={item}>{friendly(item)}</option>)}</select></Field>}
function Check({label,checked,set}:{label:string;checked:boolean;set:(value:boolean)=>void}){return <label className="flex items-center gap-2 text-sm text-primary-navy"><input checked={checked} type="checkbox" onChange={(e)=>set(e.currentTarget.checked)}/>{label}</label>}
function friendly(value:string){return value.toLowerCase().split("_").map((part)=>part.charAt(0).toUpperCase()+part.slice(1)).join(" ");}
