import { FormEvent, ReactNode, useEffect, useRef, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Button } from "../ui/components/Button";
import { WorkflowContentCard, WorkflowModal } from "../ui/components/WorkflowModal";
import type { RegistrationClient } from "./registrationClientApi";
import { createRegistrationFacilityAssignment, listRegistrationFacilityAssignments } from "./registrationFacilityAssignmentApi";
import { listRegistrationFacilities } from "./registrationFacilityApi";
import { createRegistrationPersonnel, RegistrationPersonnel, RegistrationPersonnelEmploymentStatus, registrationPersonnelEmploymentStatuses, updateRegistrationPersonnel } from "./registrationPersonnelApi";
import { openPersonnelRegistrationIntent, PersonnelRegistrationIntent, PersonnelRegistrationStep, savePersonnelRegistrationIntent } from "./personnelRegistrationJourneyApi";

type Draft={personnelType:"CLIENT";clientId:string;facilityIds:string[];primaryFacilityId:string;fullName:string;email:string;phone:string;status:RegistrationPersonnelEmploymentStatus;hireDate:string;personnelNotes:string;assignedFrom:string;assignmentNotes:string;platformAccess:"NOT_REQUIRED"|"REQUESTED"|"LINKED";platformUserId:string;createdPersonnelId:string};
const blank:Draft={personnelType:"CLIENT",clientId:"",facilityIds:[],primaryFacilityId:"",fullName:"",email:"",phone:"",status:"ACTIVE",hireDate:"",personnelNotes:"",assignedFrom:"",assignmentNotes:"",platformAccess:"NOT_REQUIRED",platformUserId:"",createdPersonnelId:""};
const steps:PersonnelRegistrationStep[]=["PERSONNEL_TYPE","CLIENT_CONTEXT","PERSONNEL_PROFILE","FACILITY_ASSIGNMENTS","PLATFORM_ACCESS","REVIEW"];
const journeySteps:PersonnelRegistrationStep[]=[...steps,"COMPLETE"];
const labels:Record<PersonnelRegistrationStep,string>={PERSONNEL_TYPE:"Personnel type",CLIENT_CONTEXT:"Client",PERSONNEL_PROFILE:"Personnel profile",FACILITY_ASSIGNMENTS:"Facility assignments",PLATFORM_ACCESS:"Platform access",REVIEW:"Review",COMPLETE:"Complete"};
const control="mt-2 min-h-11 w-full rounded-component border border-border bg-white px-3 py-2 text-sm text-text-primary outline-none focus:border-focus focus:ring-2 focus:ring-focus";

export function ClientPersonnelRegistrationWizard({clients,initialClientId,existingPersonnel,existingFacilityId,onCancel,onComplete}:{clients:readonly RegistrationClient[];initialClientId:string;existingPersonnel?:RegistrationPersonnel;existingFacilityId?:string;onCancel:()=>void;onComplete:(personnel:RegistrationPersonnel)=>void}) {
  const [intent,setIntent]=useState<PersonnelRegistrationIntent<Draft>|null>(null), [draft,setDraft]=useState<Draft>({...blank,clientId:initialClientId}), [step,setStep]=useState<PersonnelRegistrationStep>("PERSONNEL_TYPE"), [busy,setBusy]=useState(false), [error,setError]=useState<string|null>(null);
  const dialogRef=useRef<HTMLDivElement>(null), index=Math.max(0,steps.indexOf(step));
  useEffect(()=>{let active=true;openPersonnelRegistrationIntent({personnel_id:existingPersonnel?.id,client_id:existingPersonnel?.client_id??initialClientId}).then(value=>{if(!active)return;const saved={...blank,...value.draft} as Draft;if(existingFacilityId&&!saved.facilityIds.includes(existingFacilityId))saved.facilityIds.push(existingFacilityId);setIntent(value as PersonnelRegistrationIntent<Draft>);setDraft(saved);setStep(value.current_step==="COMPLETE"?"REVIEW":value.current_step)}).catch(value=>setError(value instanceof Error?value.message:"Registration could not be opened."));return()=>{active=false}},[existingPersonnel?.id,existingPersonnel?.client_id,existingFacilityId,initialClientId]);
  useEffect(()=>{dialogRef.current?.focus()},[]);
  const facilitiesQuery=useQuery({queryKey:["registration-facilities","personnel-registration",draft.clientId],queryFn:()=>listRegistrationFacilities({clientId:draft.clientId}),enabled:Boolean(draft.clientId),retry:false});
  const facilities=(facilitiesQuery.data?.facilities??[]).filter(item=>item.operational_status==="ACTIVE"), selectedClient=clients.find(item=>item.id===draft.clientId);
  const previousStep = index > 0 ? steps[index - 1] : undefined;
  const nextStep = index < steps.length - 1 ? steps[index + 1] : undefined;
  function update(patch:Partial<Draft>){setDraft(value=>({...value,...patch}));setError(null)}
  function valid(value:PersonnelRegistrationStep){return value==="CLIENT_CONTEXT"?Boolean(draft.clientId):value==="PERSONNEL_PROFILE"?Boolean(draft.fullName.trim()&&draft.hireDate):value==="FACILITY_ASSIGNMENTS"?Boolean(draft.facilityIds.length&&draft.primaryFacilityId&&draft.assignedFrom):true}
  async function persist(next:PersonnelRegistrationStep,patch:Partial<Draft>={}){if(!intent)throw new Error("Registration is still loading.");const nextDraft={...draft,...patch};const saved=await savePersonnelRegistrationIntent<Draft>(intent.id,{version:intent.version,current_step:next,draft:nextDraft,personnel_id:nextDraft.createdPersonnelId||undefined,client_id:nextDraft.clientId||undefined});setDraft(nextDraft);setIntent(saved);setStep(next)}
  async function move(next:PersonnelRegistrationStep){setBusy(true);setError(null);try{await persist(next)}catch(value){setError(value instanceof Error?value.message:"Progress could not be saved.")}finally{setBusy(false)}}
  async function close(){if(busy)return;setBusy(true);try{await persist(step);onCancel()}catch(value){setError(value instanceof Error?value.message:"Progress could not be saved.");setBusy(false)}}
  async function complete(event:FormEvent){event.preventDefault();if(step!=="REVIEW"||busy||!intent)return;setBusy(true);setError(null);try{const body={full_name:draft.fullName.trim(),email:draft.email.trim()||null,phone_number:draft.phone.trim()||null,employment_status:draft.status,hire_date:draft.hireDate||null,notes:draft.personnelNotes.trim()||null};const personnel=draft.createdPersonnelId?await updateRegistrationPersonnel(draft.createdPersonnelId,body):await createRegistrationPersonnel({...body,client_id:draft.clientId});const finalDraft={...draft,createdPersonnelId:personnel.id};let workingIntent=intent;if(!draft.createdPersonnelId){workingIntent=await savePersonnelRegistrationIntent<Draft>(intent.id,{version:intent.version,current_step:"REVIEW",draft:finalDraft,personnel_id:personnel.id,client_id:draft.clientId});setIntent(workingIntent);setDraft(finalDraft)}const existingAssignments=await listRegistrationFacilityAssignments(personnel.id);const already=new Set(existingAssignments.assignments.filter(item=>item.assignment_status==="ACTIVE").map(item=>item.facility_id));for(const facilityId of draft.facilityIds){if(!already.has(facilityId))await createRegistrationFacilityAssignment(personnel.id,{facility_id:facilityId,assigned_from:draft.assignedFrom,is_primary_assignment:facilityId===draft.primaryFacilityId,notes:draft.assignmentNotes.trim()||undefined})}await savePersonnelRegistrationIntent<Draft>(workingIntent.id,{version:workingIntent.version,current_step:"COMPLETE",draft:finalDraft,personnel_id:personnel.id,client_id:draft.clientId});onComplete(personnel)}catch(value){setError(value instanceof Error?value.message:"Registration could not be completed. Saved progress remains available.")}finally{setBusy(false)}}
  const footer=<><Button disabled={busy||!intent} onClick={close} type="button" variant="secondary">Save and close</Button><div className="flex gap-2">{previousStep?<Button disabled={busy} onClick={()=>move(previousStep)} type="button" variant="secondary">← Back</Button>:null}<Button disabled={busy||!intent||!valid(step)||(!nextStep&&step!=="REVIEW")} onClick={step==="REVIEW"?undefined:nextStep?()=>move(nextStep):undefined} type={step==="REVIEW"?"submit":"button"}>{busy?"Saving…":step==="REVIEW"?"Complete Registration":"Next →"}</Button></div></>;
  return <WorkflowModal currentStep={index} dialogRef={dialogRef} eyebrow="Registration journey" footer={footer} onKeyDown={event=>{if(event.key==="Escape")void close()}} onSubmit={complete} steps={journeySteps.map(value=>({key:value,label:labels[value]}))} title="Register Personnel" titleId="client-personnel-registration-title"><WorkflowContentCard currentLabel={labels[step]} stepNumber={index+1} totalSteps={journeySteps.length}>
    {!intent&&!error?<p className="text-sm text-text-muted">Opening saved Registration…</p>:null}
    {step==="PERSONNEL_TYPE"?<Choice detail="An employee or contractor governed by one Client. OGI Personnel use the separate OGI authority journey." selected title="Client Personnel"/>:null}
    {step==="CLIENT_CONTEXT"?<Field label="Governing Client"><select className={control} disabled={Boolean(draft.createdPersonnelId)} value={draft.clientId} onChange={event=>update({clientId:event.currentTarget.value,facilityIds:[],primaryFacilityId:""})}><option value="">Select a Client</option>{clients.filter(item=>item.status==="ACTIVE").map(item=><option key={item.id} value={item.id}>{item.organization_name}</option>)}</select></Field>:null}
    {step==="PERSONNEL_PROFILE"?<div className="grid gap-4 md:grid-cols-2"><Input label="Full name" value={draft.fullName} onChange={fullName=>update({fullName})}/><Input label="Email" type="email" value={draft.email} onChange={email=>update({email})}/><Input label="Phone" value={draft.phone} onChange={phone=>update({phone})}/><Field label="Employment status"><select className={control} value={draft.status} onChange={event=>update({status:event.currentTarget.value as RegistrationPersonnelEmploymentStatus})}>{registrationPersonnelEmploymentStatuses.map(value=><option key={value}>{value}</option>)}</select></Field><Input label="Hire date" type="date" value={draft.hireDate} onChange={hireDate=>update({hireDate})}/><Input label="Personnel notes" value={draft.personnelNotes} onChange={personnelNotes=>update({personnelNotes})}/></div>:null}
    {step==="FACILITY_ASSIGNMENTS"?<div className="space-y-4"><p className="text-sm text-text-muted">Assign one or more active Facilities for {selectedClient?.organization_name??"the selected Client"}. Select one as primary.</p><div className="grid gap-3 md:grid-cols-2">{facilities.map(facility=><FacilityChoice key={facility.id} name={facility.facility_name} checked={draft.facilityIds.includes(facility.id)} primary={draft.primaryFacilityId===facility.id} onChecked={checked=>{const ids=checked?[...draft.facilityIds,facility.id]:draft.facilityIds.filter(id=>id!==facility.id);update({facilityIds:ids,primaryFacilityId:checked&&!draft.primaryFacilityId?facility.id:draft.primaryFacilityId===facility.id?ids[0]??"":draft.primaryFacilityId})}} onPrimary={()=>update({primaryFacilityId:facility.id})}/>)}</div>{facilitiesQuery.isError?<p className="text-sm text-state-error">Facilities could not be loaded.</p>:null}<Input label="Assignment starts" type="date" value={draft.assignedFrom} onChange={assignedFrom=>update({assignedFrom})}/><Input label="Assignment notes" value={draft.assignmentNotes} onChange={assignmentNotes=>update({assignmentNotes})}/></div>:null}
    {step==="PLATFORM_ACCESS"?<div className="space-y-3"><p className="text-sm text-text-muted">Login access is optional and separate from employment.</p><Choice detail="Complete Registration without creating or linking a login." onClick={()=>update({platformAccess:"NOT_REQUIRED"})} selected={draft.platformAccess==="NOT_REQUIRED"} title="No platform access"/><Choice detail="Record a request for an administrator to fulfill through governed account provisioning." onClick={()=>update({platformAccess:"REQUESTED"})} selected={draft.platformAccess==="REQUESTED"} title="Request platform access"/>{draft.platformAccess==="LINKED"?<Choice detail="This Personnel record already has platform access." selected title="Existing account linked"/>:null}</div>:null}
    {step==="REVIEW"?<div className="space-y-4"><dl className="grid gap-4 rounded-component bg-elevated p-4 sm:grid-cols-2"><Summary label="Personnel type" value="Client Personnel"/><Summary label="Client" value={selectedClient?.organization_name}/><Summary label="Personnel" value={draft.fullName}/><Summary label="Employment" value={draft.status}/><Summary label="Facilities" value={draft.facilityIds.map(id=>facilities.find(item=>item.id===id)?.facility_name).filter(Boolean).join(", ")}/><Summary label="Primary Facility" value={facilities.find(item=>item.id===draft.primaryFacilityId)?.facility_name}/><Summary label="Assignment begins" value={draft.assignedFrom}/><Summary label="Platform access" value={draft.platformAccess==="REQUESTED"?"Provisioning requested":draft.platformAccess==="LINKED"?"Linked":"Not required"}/></dl><p className="rounded-component border border-blue-200 bg-blue-50 p-3 text-sm text-primary-navy">Training enrollment remains a separate journey.</p></div>:null}
    {error?<p className="mt-5 rounded-component border border-red-200 bg-red-50 p-3 text-sm text-red-800" role="alert">{error}</p>:null}
  </WorkflowContentCard></WorkflowModal>
}
function FacilityChoice({name,checked,primary,onChecked,onPrimary}:{name:string;checked:boolean;primary:boolean;onChecked:(value:boolean)=>void;onPrimary:()=>void}){return <div className={`rounded-component border p-4 ${checked?"border-primary-blue bg-blue-50":"border-border"}`}><label className="flex gap-3 font-semibold text-primary-navy"><input checked={checked} onChange={event=>onChecked(event.currentTarget.checked)} type="checkbox"/>{name}</label>{checked?<label className="mt-3 flex gap-2 text-sm text-text-muted"><input checked={primary} name="primaryFacility" onChange={onPrimary} type="radio"/>Primary Facility</label>:null}</div>}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="block text-sm font-semibold text-primary-navy">{label}{children}</label>}
function Input({label,value,onChange,type="text"}:{label:string;value:string;onChange:(value:string)=>void;type?:string}){return <Field label={label}><input className={control} type={type} value={value} onChange={event=>onChange(event.currentTarget.value)}/></Field>}
function Summary({label,value}:{label:string;value?:string}){return <div><dt className="text-xs font-bold uppercase tracking-wide text-text-muted">{label}</dt><dd className="mt-1 font-semibold text-primary-navy">{value||"Not supplied"}</dd></div>}
function Choice({title,detail,selected,onClick}:{title:string;detail:string;selected:boolean;onClick?:()=>void}){return <button className={`w-full rounded-component border p-4 text-left ${selected?"border-primary-blue bg-blue-50 ring-1 ring-primary-blue":"border-border bg-white"}`} onClick={onClick} type="button"><span className="font-semibold text-primary-navy">{title}</span><span className="mt-1 block text-sm text-text-muted">{detail}</span></button>}
