import { apiRequest } from "../api/client";

export type PersonnelRegistrationStep = "PERSONNEL_TYPE" | "CLIENT_CONTEXT" | "PERSONNEL_PROFILE" | "FACILITY_ASSIGNMENTS" | "PLATFORM_ACCESS" | "REVIEW" | "COMPLETE";
export interface PersonnelRegistrationIntent<T extends object = Record<string, unknown>> { id:string; personnel_id:string|null; client_id:string|null; status:"IN_PROGRESS"|"COMPLETED"|"CANCELLED"; current_step:PersonnelRegistrationStep; draft:T; version:number; completed_at:string|null; created_at:string; updated_at:string }
const isIntent = (value:unknown):value is PersonnelRegistrationIntent => Boolean(value && typeof value === "object" && typeof (value as PersonnelRegistrationIntent).id === "string" && typeof (value as PersonnelRegistrationIntent).version === "number" && typeof (value as PersonnelRegistrationIntent).current_step === "string");
export function openPersonnelRegistrationIntent(input:{personnel_id?:string;client_id?:string}) { return apiRequest<PersonnelRegistrationIntent>("/api/v1/registration/personnel-registration-intents/open", {method:"POST", body:input, validate:isIntent}); }
export function savePersonnelRegistrationIntent<T extends object>(id:string,input:{version:number;current_step:PersonnelRegistrationStep;draft:T;personnel_id?:string;client_id?:string}) { return apiRequest<PersonnelRegistrationIntent<T>>(`/api/v1/registration/personnel-registration-intents/${encodeURIComponent(id)}`, {method:"PATCH", body:input, validate:isIntent as (value:unknown)=>value is PersonnelRegistrationIntent<T>}); }
export function getPersonnelRegistrationIntent(personnelId:string) { return apiRequest<{intent:PersonnelRegistrationIntent|null}>(`/api/v1/registration/personnel-registration-intents/personnel/${encodeURIComponent(personnelId)}`, {validate:(value):value is {intent:PersonnelRegistrationIntent|null}=>Boolean(value&&typeof value==="object"&&("intent" in value)&&((value as {intent:unknown}).intent===null||isIntent((value as {intent:unknown}).intent)))}); }
export function getCurrentPersonnelRegistrationIntent() { return apiRequest<{intent:PersonnelRegistrationIntent|null}>("/api/v1/registration/personnel-registration-intents/current", {validate:(value):value is {intent:PersonnelRegistrationIntent|null}=>Boolean(value&&typeof value==="object"&&("intent" in value)&&((value as {intent:unknown}).intent===null||isIntent((value as {intent:unknown}).intent)))}); }
