import { FormEvent, type ReactNode, useState } from "react";
import { Link, useNavigate, useSearchParams } from "react-router-dom";
import { confirmPasswordReset, requestPasswordReset } from "../../auth/authApi";
import { routes } from "../routePaths";

const shell="relative min-h-screen overflow-hidden bg-cover bg-center bg-no-repeat px-5 py-8 sm:px-8 lg:bg-contain lg:bg-bottom";
const card="relative mx-auto mt-[8vh] w-full max-w-lg rounded-[1rem] border border-white/80 bg-white/[0.9] p-7 shadow-panel backdrop-blur-md sm:p-10";
const input="mt-2 min-h-12 w-full rounded-lg border border-blue-200 bg-blue-50/70 px-4 outline-none focus:border-focus focus:ring-2 focus:ring-focus";
const button="min-h-12 w-full rounded-lg bg-primary-blue px-4 font-semibold text-white hover:bg-primary-navy disabled:opacity-70";

function PageShell({children}:{children:ReactNode}){return <main className={shell} style={{backgroundImage:"url('/brand/LoginBackround.png')"}}><div className="absolute inset-0 bg-gradient-to-r from-white/45 via-blue-50/40 to-white/70" aria-hidden="true"/>{children}</main>}

export function ForgotPasswordPage(){const[identifier,setIdentifier]=useState(""),[submitted,setSubmitted]=useState(false),[error,setError]=useState<string|null>(null),[busy,setBusy]=useState(false);async function submit(event:FormEvent){event.preventDefault();if(!identifier.trim())return;setError(null);setBusy(true);try{await requestPasswordReset(identifier.trim());setSubmitted(true)}catch{setError("We couldn't process the request right now. Please try again.")}finally{setBusy(false)}}return <PageShell><section className={card} aria-labelledby="forgot-heading"><p className="text-sm font-semibold uppercase tracking-wide text-primary-blue">Secure access</p><h1 id="forgot-heading" className="mt-2 text-3xl font-semibold text-primary-navy">Reset your password</h1>{submitted?<><p role="status" className="mt-6 leading-7 text-text-muted">If an eligible account matches that information, password reset instructions have been sent.</p><Link className="mt-6 inline-block font-semibold text-primary-blue" to={routes.login}>Return to Sign In</Link></>:<form className="mt-7 space-y-6" onSubmit={submit}><div><label className="font-semibold text-primary-navy" htmlFor="reset-identifier">Email or Username</label><input className={input} id="reset-identifier" value={identifier} onChange={event=>setIdentifier(event.target.value)} autoComplete="username"/></div>{error?<p role="alert" className="text-sm text-state-error">{error}</p>:null}<button className={button} disabled={busy} type="submit">{busy?"Sending...":"Send reset instructions"}</button><Link className="block text-center text-sm font-semibold text-primary-blue" to={routes.login}>Back to Sign In</Link></form>}</section></PageShell>}

export function ResetPasswordPage(){const[params]=useSearchParams(),navigate=useNavigate(),token=params.get("token")??"",[password,setPassword]=useState(""),[confirm,setConfirm]=useState(""),[error,setError]=useState<string|null>(null),[done,setDone]=useState(false),[busy,setBusy]=useState(false);async function submit(event:FormEvent){event.preventDefault();setError(null);if(!token){setError("This password reset link is invalid or expired.");return}if(password!==confirm){setError("Passwords do not match.");return}if(password.length<8){setError("Password must contain at least 8 characters.");return}setBusy(true);try{await confirmPasswordReset(token,password);setPassword("");setConfirm("");setDone(true);navigate(routes.resetPassword,{replace:true})}catch{setError("This password reset link is invalid or expired.")}finally{setBusy(false)}}return <PageShell><section className={card} aria-labelledby="reset-heading"><p className="text-sm font-semibold uppercase tracking-wide text-primary-blue">Secure access</p><h1 id="reset-heading" className="mt-2 text-3xl font-semibold text-primary-navy">Choose a new password</h1>{done?<><p role="status" className="mt-6 text-text-muted">Your password has been reset. Sign in with your new password.</p><Link className="mt-6 inline-block font-semibold text-primary-blue" to={routes.login}>Continue to Sign In</Link></>:<form className="mt-7 space-y-5" onSubmit={submit}><div><label className="font-semibold text-primary-navy" htmlFor="new-password">New password</label><input className={input} id="new-password" type="password" autoComplete="new-password" value={password} onChange={event=>setPassword(event.target.value)}/></div><div><label className="font-semibold text-primary-navy" htmlFor="confirm-password">Confirm new password</label><input className={input} id="confirm-password" type="password" autoComplete="new-password" value={confirm} onChange={event=>setConfirm(event.target.value)}/></div>{error?<p role="alert" className="text-sm text-state-error">{error}</p>:null}<button className={button} disabled={busy} type="submit">{busy?"Resetting...":"Reset password"}</button></form>}</section></PageShell>}
