import { apiRequest } from "../api/client";

export const assetCategories=["RESCUE_EQUIPMENT","MEDICAL_EQUIPMENT","AED","OXYGEN_EQUIPMENT","WATERCRAFT","COMMUNICATIONS_EQUIPMENT","SAFETY_EQUIPMENT","VEHICLE","TRAINING_EQUIPMENT","ADMINISTRATIVE_EQUIPMENT","OTHER"] as const;
export const assetLifecycleStatuses=["ACTIVE","IN_SERVICE","RESTRICTED","UNDER_MAINTENANCE","OUT_OF_SERVICE","RETIRED","DISPOSED"] as const;
export type AssetCategory=typeof assetCategories[number];
export type AssetLifecycleStatus=typeof assetLifecycleStatuses[number];
export const assetApplicabilityStatuses=["UNSPECIFIED","APPLICABLE","NOT_APPLICABLE"] as const;
export type AssetApplicabilityStatus=typeof assetApplicabilityStatuses[number];
export interface AssetRegistryRecord{asset_id:string;business_identifier:string;client_id:string;facility_id:string;equipment_name:string;equipment_category:AssetCategory;equipment_subtype:string|null;manufacturer:string|null;model_number:string|null;serial_number:string|null;assigned_location:string|null;assigned_custodian:string|null;placed_in_service_date:string|null;preventive_maintenance_applicability:AssetApplicabilityStatus;rescue_inspection_applicability:AssetApplicabilityStatus;calibration_applicability:AssetApplicabilityStatus;lifecycle_status:AssetLifecycleStatus;created_by_user_id:string;created_at:string;}
export interface CreateAssetRequest{facility_id:string;equipment_name:string;equipment_category:AssetCategory;equipment_subtype?:string;manufacturer?:string;model_number?:string;serial_number?:string;assigned_location?:string;assigned_custodian?:string;placed_in_service_date?:string;lifecycle_status:AssetLifecycleStatus;}
export interface AssetRegistryPage{assets:AssetRegistryRecord[];count:number;next_cursor:string|null;}

export function createAsset(request:CreateAssetRequest){return apiRequest<{success:true;data:AssetRegistryRecord}>("/api/v1/assets",{method:"POST",body:request,validate:isRecordResponse}).then(value=>value.data);}
export function listAssets(input:{facilityId:string;query?:string;limit?:number;cursor?:string}){const query=new URLSearchParams({facility_id:input.facilityId,limit:String(input.limit??25)});if(input.query)query.set("query",input.query);if(input.cursor)query.set("cursor",input.cursor);return apiRequest<{success:true;data:AssetRegistryPage}>(`/api/v1/assets?${query}`,{validate:isPageResponse}).then(value=>value.data);}
export function getAsset(assetId:string){return apiRequest<{success:true;data:AssetRegistryRecord}>(`/api/v1/assets/${encodeURIComponent(assetId)}`,{validate:isRecordResponse}).then(value=>value.data);}
export function updateAssetApplicability(assetId:string,request:{preventive_maintenance_applicability:AssetApplicabilityStatus;rescue_inspection_applicability:AssetApplicabilityStatus;calibration_applicability:AssetApplicabilityStatus;expected:{preventive_maintenance_applicability:AssetApplicabilityStatus;rescue_inspection_applicability:AssetApplicabilityStatus;calibration_applicability:AssetApplicabilityStatus};rationale:string;idempotency_key:string}){return apiRequest<{success:true;data:AssetRegistryRecord}>(`/api/v1/assets/${encodeURIComponent(assetId)}/applicability`,{method:"PATCH",body:request,validate:isRecordResponse}).then(value=>value.data);}
function object(value:unknown):value is Record<string,unknown>{return value!==null&&typeof value==="object"&&!Array.isArray(value);}
function asset(value:unknown):value is AssetRegistryRecord{return object(value)&&typeof value.asset_id==="string"&&typeof value.business_identifier==="string"&&typeof value.facility_id==="string"&&typeof value.equipment_name==="string"&&typeof value.equipment_category==="string"&&typeof value.lifecycle_status==="string"&&typeof value.preventive_maintenance_applicability==="string"&&typeof value.rescue_inspection_applicability==="string"&&typeof value.calibration_applicability==="string";}
function isRecordResponse(value:unknown):value is {success:true;data:AssetRegistryRecord}{return object(value)&&value.success===true&&asset(value.data);}
function isPageResponse(value:unknown):value is {success:true;data:AssetRegistryPage}{return object(value)&&value.success===true&&object(value.data)&&Array.isArray(value.data.assets)&&value.data.assets.every(asset)&&typeof value.data.count==="number"&&(value.data.next_cursor===null||typeof value.data.next_cursor==="string");}
