import { QueryClient,QueryClientProvider } from "@tanstack/react-query";
import { render,screen,waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { afterEach,expect,it,vi } from "vitest";
import { AssetRegistrationPanel } from "./AssetRegistrationPanel";

afterEach(()=>vi.unstubAllGlobals());
it("registers an Asset through the governed registry without selecting an OETS context",async()=>{const user=userEvent.setup(),onCreated=vi.fn(),record={asset_id:"40000000-0000-4000-8000-000000000001",business_identifier:"ASSET-2026-000001",client_id:"20000000-0000-4000-8000-000000000001",facility_id:"30000000-0000-4000-8000-000000000001",equipment_name:"Rescue Tube 1",equipment_category:"RESCUE_EQUIPMENT",equipment_subtype:null,manufacturer:null,model_number:null,serial_number:null,assigned_location:null,assigned_custodian:null,placed_in_service_date:null,preventive_maintenance_applicability:"UNSPECIFIED",rescue_inspection_applicability:"UNSPECIFIED",calibration_applicability:"UNSPECIFIED",lifecycle_status:"ACTIVE",created_by_user_id:"10000000-0000-4000-8000-000000000001",created_at:"2026-09-16T00:00:00.000Z"};const fetchMock=vi.fn().mockResolvedValue(new Response(JSON.stringify({success:true,data:record}),{status:200,headers:{"Content-Type":"application/json"}}));vi.stubGlobal("fetch",fetchMock);render(<QueryClientProvider client={new QueryClient({defaultOptions:{mutations:{retry:false}}})}><AssetRegistrationPanel facilityId={record.facility_id} onCreated={onCreated}/></QueryClientProvider>);await user.click(screen.getByRole("button",{name:"Register New Asset"}));await user.type(screen.getByLabelText("Equipment name"),"Rescue Tube 1");await user.click(screen.getByRole("button",{name:"Register Asset"}));await waitFor(()=>expect(onCreated).toHaveBeenCalledWith(record));const body=JSON.parse(String((fetchMock.mock.calls[0]?.[1] as RequestInit).body));expect(body).toMatchObject({facility_id:record.facility_id,equipment_name:"Rescue Tube 1",equipment_category:"RESCUE_EQUIPMENT",lifecycle_status:"ACTIVE"});expect(String(fetchMock.mock.calls[0]?.[0])).toContain("/api/v1/assets");});
it("keeps registration unavailable when its caller has not authorized it",()=>{render(<QueryClientProvider client={new QueryClient()}><AssetRegistrationPanel disabled facilityId="30000000-0000-4000-8000-000000000001" onCreated={()=>{}}/></QueryClientProvider>);expect(screen.getByRole("button",{name:"Register New Asset"})).toBeDisabled();});
