import { type FormEvent,type ReactNode,useState } from "react";
import { useMutation } from "@tanstack/react-query";
import { isApiError } from "../api/errors";
import { Button } from "../ui/components/Button";
import { humanizeDisplayCode } from "../ui/displayText";
import { assetCategories,createAsset,type AssetCategory,type AssetRegistryRecord } from "./assetRegistryApi";

const initial={name:"",category:"RESCUE_EQUIPMENT" as AssetCategory,subtype:"",manufacturer:"",model:"",serial:"",location:"",custodian:"",serviceDate:""};
export function AssetRegistrationPanel({facilityId,disabled=false,onCreated}:{readonly facilityId:string;readonly disabled?:boolean;readonly onCreated:(asset:AssetRegistryRecord)=>void}){
 const[open,setOpen]=useState(false),[form,setForm]=useState(initial),[message,setMessage]=useState<string|null>(null);
 const mutation=useMutation({mutationFn:createAsset,onSuccess:asset=>{setMessage(`Asset ${asset.business_identifier} registered.`);setForm(initial);setOpen(false);onCreated(asset);},onError:error=>setMessage(isApiError(error)?error.message:"The Asset could not be registered.")});
 function submit(event:FormEvent){event.preventDefault();setMessage(null);if(!form.name.trim()){setMessage("Equipment name is required.");return;}const optional=(value:string)=>value.trim()||undefined;mutation.mutate({facility_id:facilityId,equipment_name:form.name.trim(),equipment_category:form.category,equipment_subtype:optional(form.subtype),manufacturer:optional(form.manufacturer),model_number:optional(form.model),serial_number:optional(form.serial),assigned_location:optional(form.location),assigned_custodian:optional(form.custodian),placed_in_service_date:optional(form.serviceDate),lifecycle_status:"ACTIVE"});}
 if(!open)return <div><Button disabled={disabled||!facilityId} onClick={()=>{setOpen(true);setMessage(null);}} type="button" variant="secondary">Register New Asset</Button>{message?<p className="mt-2 text-sm text-teal-700" role="status">{message}</p>:null}</div>;
 return <form className="space-y-4 rounded-component border border-blue-200 bg-white p-4" onSubmit={submit}><div><h3 className="font-semibold text-primary-navy">Register Asset</h3><p className="mt-1 text-sm text-text-muted">The Asset identifier and creator provenance are assigned by the governed registry.</p></div><div className="grid gap-4 md:grid-cols-2">
  <Field label="Equipment name"><input className={control} required value={form.name} onChange={e=>setForm({...form,name:e.currentTarget.value})}/></Field>
  <Field label="Equipment category"><select className={control} value={form.category} onChange={e=>setForm({...form,category:e.currentTarget.value as AssetCategory})}>{assetCategories.map(value=><option key={value} value={value}>{friendly(value)}</option>)}</select></Field>
  <Field label="Equipment subtype"><input className={control} value={form.subtype} onChange={e=>setForm({...form,subtype:e.currentTarget.value})}/></Field><Field label="Manufacturer"><input className={control} value={form.manufacturer} onChange={e=>setForm({...form,manufacturer:e.currentTarget.value})}/></Field><Field label="Model number"><input className={control} value={form.model} onChange={e=>setForm({...form,model:e.currentTarget.value})}/></Field><Field label="Serial number"><input className={control} value={form.serial} onChange={e=>setForm({...form,serial:e.currentTarget.value})}/></Field><Field label="Assigned location"><input className={control} value={form.location} onChange={e=>setForm({...form,location:e.currentTarget.value})}/></Field><Field label="Assigned custodian"><input className={control} value={form.custodian} onChange={e=>setForm({...form,custodian:e.currentTarget.value})}/></Field><Field label="Date placed into service"><input className={control} type="date" value={form.serviceDate} onChange={e=>setForm({...form,serviceDate:e.currentTarget.value})}/></Field>
 </div>{message?<p className="text-sm text-red-700" role="alert">{message}</p>:null}<div className="flex gap-2"><Button disabled={mutation.isPending} type="submit">{mutation.isPending?"Registering…":"Register Asset"}</Button><Button disabled={mutation.isPending} onClick={()=>{setOpen(false);setMessage(null);}} type="button" variant="secondary">Cancel</Button></div></form>;
}
const control="mt-2 min-h-10 w-full rounded-component border border-border bg-white px-3 py-2 text-sm";
function Field({label,children}:{label:string;children:ReactNode}){return <label className="text-sm font-semibold text-primary-navy">{label}{children}</label>}
function friendly(value:string){return humanizeDisplayCode(value);}
