import { useState } from "react";
import { useMutation } from "@tanstack/react-query";
import { isApiError } from "../api/errors";
import { Button } from "../ui/components/Button";
import { assetApplicabilityStatuses,getAsset,updateAssetApplicability,type AssetApplicabilityStatus,type AssetRegistryRecord } from "./assetRegistryApi";

export function AssetApplicabilityPanel({assetId,onUpdated}:{assetId:string;onUpdated?: (asset:AssetRegistryRecord)=>void}){
  const[asset,setAsset]=useState<AssetRegistryRecord|null>(null),[open,setOpen]=useState(false),[rationale,setRationale]=useState(""),[message,setMessage]=useState<string|null>(null);
  const[values,setValues]=useState({preventive_maintenance_applicability:"UNSPECIFIED" as AssetApplicabilityStatus,rescue_inspection_applicability:"UNSPECIFIED" as AssetApplicabilityStatus,calibration_applicability:"UNSPECIFIED" as AssetApplicabilityStatus});
  const load=useMutation({mutationFn:()=>getAsset(assetId),onSuccess:value=>{setAsset(value);setValues(pick(value));setOpen(true);setMessage(null);},onError:error=>setMessage(isApiError(error)?error.message:"Asset applicability could not be loaded.")});
  const save=useMutation({mutationFn:()=>updateAssetApplicability(assetId,{...values,expected:pick(asset!),rationale:rationale.trim(),idempotency_key:crypto.randomUUID()}),onSuccess:value=>{setAsset(value);setValues(pick(value));setRationale("");setMessage("Applicability authority saved.");onUpdated?.(value);},onError:error=>setMessage(isApiError(error)?error.message:"Asset applicability could not be saved.")});
  if(!open)return <span><button className="text-sm font-semibold text-primary-blue underline" disabled={load.isPending} onClick={()=>load.mutate()} type="button">Set applicability</button>{message?<span className="ml-2 text-xs text-red-700" role="alert">{message}</span>:null}</span>;
  return <div className="w-full min-w-[18rem] rounded-component border border-blue-200 bg-blue-50 p-3"><p className="text-sm font-semibold text-primary-navy">Governed form applicability</p><p className="mt-1 text-xs text-text-muted">Unspecified remains ineligible. Set only from known equipment requirements.</p><div className="mt-2 grid gap-2">{([['preventive_maintenance_applicability','F082 preventive maintenance'],['rescue_inspection_applicability','F086 rescue inspection'],['calibration_applicability','F087 calibration']] as const).map(([field,label])=><label className="text-xs font-semibold text-primary-navy" key={field}>{label}<select className="ml-2 rounded border border-border bg-white px-2 py-1" value={values[field]} onChange={event=>setValues({...values,[field]:event.currentTarget.value as AssetApplicabilityStatus})}>{assetApplicabilityStatuses.map(status=><option key={status} value={status}>{status.replaceAll('_',' ')}</option>)}</select></label>)}</div><label className="mt-2 block text-xs font-semibold text-primary-navy">Rationale<input className="mt-1 w-full rounded border border-border bg-white px-2 py-1" value={rationale} onChange={event=>setRationale(event.currentTarget.value)}/></label>{message?<p className="mt-2 text-xs text-teal-700" role="status">{message}</p>:null}<div className="mt-2 flex gap-2"><Button disabled={save.isPending||!rationale.trim()} onClick={()=>save.mutate()} type="button">Save applicability</Button><Button disabled={save.isPending} onClick={()=>{setOpen(false);setMessage(null);}} type="button" variant="secondary">Close</Button></div></div>;
}
function pick(asset:AssetRegistryRecord){return{preventive_maintenance_applicability:asset.preventive_maintenance_applicability,rescue_inspection_applicability:asset.rescue_inspection_applicability,calibration_applicability:asset.calibration_applicability};}
