import { useQuery } from "@tanstack/react-query";
import { Link, useParams, useSearchParams } from "react-router-dom";

import { isApiError } from "../api/errors";
import { routes } from "../app/routePaths";
import { useCan } from "../auth/useCan";
import { Button } from "../ui/components/Button";
import { Surface } from "../ui/components/Surface";
import { auditFindingQueryKeys, getAuditFinding, listAuditFindings } from "./auditRiskApi";
import { AuditState, Context } from "./AuditRiskWorkspacePage";
import { AuditRiskNavigation } from "./AuditRiskNavigation";
import { AuditRiskMetadataGrid, AuditRiskPageHeader, AuditRiskRecordCard, AuditRiskRecordCollection, AuditRiskSectionCard, AuditRiskStatusBadge } from "./AuditRiskUi";
import { AuditFindingReadProjection, AuditFindingSeverity, auditFindingSeverities, displayCode, formatDateTime } from "./auditRiskTypes";

export function AuditFindingsPage() {
  const canView = useCan("view_finding");
  const canViewAudit = useCan("view_audit");
  const [searchParams, setSearchParams] = useSearchParams();
  const requestedSeverity = searchParams.get("severity");
  const severity = auditFindingSeverities.includes(requestedSeverity as AuditFindingSeverity)
    ? (requestedSeverity as AuditFindingSeverity)
    : undefined;
  const requestedResolved = searchParams.get("resolved");
  const resolved = requestedResolved === "true" ? true : requestedResolved === "false" ? false : undefined;
  const filters = { ...(severity ? { severity } : {}), ...(resolved === undefined ? {} : { resolved }) };
  const query = useQuery({
    queryKey: auditFindingQueryKeys.list(filters),
    queryFn: () => listAuditFindings(filters),
    enabled: canView,
    retry: false
  });

  if (!canView) return <AuditState title="You are not authorized to view Audit Findings.">Your current session does not include Finding viewing authority.</AuditState>;

  return (
    <section aria-labelledby="audit-findings-heading" className="space-y-4">
      <AuditRiskNavigation />
      <AuditRiskPageHeader eyebrow="Audit & Risk" headingId="audit-findings-heading" summary="Review scoped Findings generated by Audit processing. Remediation relationships are reference-only." title="Findings" />
      <FindingFilters
        resolved={resolved}
        severity={severity}
        onChange={(nextSeverity, nextResolved) => {
          const next = new URLSearchParams();
          if (nextSeverity) next.set("severity", nextSeverity);
          if (nextResolved !== undefined) next.set("resolved", String(nextResolved));
          setSearchParams(next, { replace: true });
        }}
      />
      {query.isLoading ? (
        <AuditState role="status" title="Loading Audit Findings.">Please wait.</AuditState>
      ) : query.isError ? (
        <FindingError error={query.error} onRetry={() => void query.refetch()} />
      ) : !query.data || query.data.findings.length === 0 ? (
        <AuditState title="No Audit Findings are available.">No Findings matched your current filters and authority.</AuditState>
      ) : (
        <FindingList canViewAudit={canViewAudit} findings={query.data.findings} />
      )}
    </section>
  );
}

export function AuditFindingDetailPage() {
  const canView = useCan("view_finding");
  const canViewAudit = useCan("view_audit");
  const { findingId } = useParams();
  const query = useQuery({
    queryKey: auditFindingQueryKeys.detail(findingId ?? ""),
    queryFn: () => getAuditFinding(findingId ?? ""),
    enabled: canView && Boolean(findingId),
    retry: false
  });

  if (!canView) return <AuditState title="You are not authorized to view Audit Findings.">Your current session does not include Finding viewing authority.</AuditState>;
  if (!findingId) return <AuditState title="Audit Finding unavailable.">No Finding identifier was provided.</AuditState>;
  if (query.isLoading) return <AuditState role="status" title="Loading Audit Finding detail.">Please wait.</AuditState>;
  if (query.isError) return <FindingError detail error={query.error} onRetry={() => void query.refetch()} />;
  if (!query.data) return <AuditState title="Audit Finding unavailable.">The Finding service did not return authoritative detail.</AuditState>;

  const finding = query.data;
  return (
    <section aria-labelledby="audit-finding-detail-heading" className="space-y-4">
      <AuditRiskNavigation />
      <Link className="text-sm font-semibold text-primary-blue hover:underline" to={routes.auditFindings}>← Back to Findings</Link>
      <AuditRiskPageHeader eyebrow="Audit & Risk · Finding" headingId="audit-finding-detail-heading" summary={finding.title} title={finding.business_identifier} status={<div className="flex flex-wrap gap-2"><AuditRiskStatusBadge value={finding.severity} /><AuditRiskStatusBadge value={finding.is_resolved ? "RESOLVED" : "UNRESOLVED"} /></div>} />
      <Surface className="border-blue-100 bg-blue-50/60 shadow-none">
        <AuditRiskMetadataGrid>
          <Context label="Category" value={finding.category} />
          <Context label="Client" value={`${finding.client.name} · ${finding.client.business_identifier}`} />
          <Context label="Facility" value={`${finding.facility.name} · ${finding.facility.business_identifier}`} />
          <div><dt className="text-xs font-semibold uppercase tracking-wide text-text-muted">Parent Audit</dt><dd className="mt-1 text-text-primary">{canViewAudit ? <Link className="text-primary-blue hover:underline" to={routes.auditDetailPath(finding.audit.id)}>{finding.audit.business_identifier}</Link> : finding.audit.business_identifier}</dd></div>
          <Context label="Identified" value={formatDateTime(finding.identified_at)} />
          <Context label="Resolved" value={finding.resolved_at ? formatDateTime(finding.resolved_at) : "Not resolved"} />
        </AuditRiskMetadataGrid>
      </Surface>
      <AuditRiskSectionCard heading="Finding narrative" headingId="finding-narrative-heading">
        <dl className="mt-4 space-y-4">
          <Context label="Description" value={finding.description} />
          <Context label="Recommendation" value={finding.recommendation ?? "No recommendation recorded"} />
        </dl>
      </AuditRiskSectionCard>
      <RemediationRelationships remediation={finding.remediation} />
    </section>
  );
}

function FindingFilters({ onChange, resolved, severity }: {
  onChange: (severity: AuditFindingSeverity | undefined, resolved: boolean | undefined) => void;
  resolved: boolean | undefined;
  severity: AuditFindingSeverity | undefined;
}) {
  return (
    <Surface className="border-[#C9D7E8] bg-[#DDE8F4] shadow-none">
      <div className="grid gap-4 md:grid-cols-2">
        <label className="block text-sm font-semibold text-primary-navy"><span className="block">Severity</span><select className="mt-2 min-h-11 w-full rounded-component border border-blue-200 bg-white px-3 outline-none hover:border-primary-blue focus-visible:ring-2 focus-visible:ring-focus" onChange={(event) => onChange((event.currentTarget.value || undefined) as AuditFindingSeverity | undefined, resolved)} value={severity ?? ""}><option value="">All severities</option>{auditFindingSeverities.map((value) => <option key={value} value={value}>{displayCode(value)}</option>)}</select></label>
        <label className="block text-sm font-semibold text-primary-navy"><span className="block">Resolution</span><select className="mt-2 min-h-11 w-full rounded-component border border-blue-200 bg-white px-3 outline-none hover:border-primary-blue focus-visible:ring-2 focus-visible:ring-focus" onChange={(event) => onChange(severity, event.currentTarget.value === "" ? undefined : event.currentTarget.value === "true")} value={resolved === undefined ? "" : String(resolved)}><option value="">All resolution states</option><option value="false">Unresolved</option><option value="true">Resolved</option></select></label>
      </div>
    </Surface>
  );
}

function FindingList({ canViewAudit, findings }: { canViewAudit: boolean; findings: readonly AuditFindingReadProjection[] }) {
  return (
    <AuditRiskRecordCollection label="Scoped Audit Findings">
        {findings.map((finding) => (
          <li key={finding.id}>
            <AuditRiskRecordCard labelledBy={`finding-${finding.id}`}>
              <div className="space-y-4">
              <div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0"><h2 className="break-words text-lg font-semibold text-primary-navy" id={`finding-${finding.id}`}>{finding.title}</h2><Link className="mt-1 inline-block break-words text-sm font-semibold text-primary-blue hover:underline focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-focus" to={routes.auditFindingDetailPath(finding.id)}>{finding.business_identifier}</Link><p className="mt-2 text-sm font-semibold text-text-primary">{finding.facility.name}</p><p className="text-sm text-text-muted">{finding.client.name}</p></div><div className="flex flex-wrap justify-end gap-2"><AuditRiskStatusBadge value={finding.severity} /><AuditRiskStatusBadge value={finding.is_resolved ? "RESOLVED" : "UNRESOLVED"} /></div></div>
              <dl className="grid gap-2 text-sm sm:grid-cols-2"><div><dt className="text-xs font-semibold uppercase tracking-wide text-text-muted">Parent Audit</dt><dd className="mt-1 text-text-primary">{canViewAudit ? <Link className="text-primary-blue hover:underline" to={routes.auditDetailPath(finding.audit.id)}>{finding.audit.business_identifier}</Link> : finding.audit.business_identifier}</dd></div><Context label="Identified" value={formatDateTime(finding.identified_at)} /></dl>
              </div>
            </AuditRiskRecordCard>
          </li>
        ))}
    </AuditRiskRecordCollection>
  );
}

function RemediationRelationships({ remediation }: { remediation: AuditFindingReadProjection["remediation"] }) {
  return (
    <AuditRiskSectionCard heading="Remediation relationships" headingId="remediation-relationships-heading">
      {remediation.length === 0 ? <p className="text-sm text-text-muted">No Corrective Action relationships are recorded.</p> : <ul aria-label="Read-only remediation relationships" className="space-y-3">{remediation.map((relationship) => <li className="rounded-component border border-border bg-canvas p-3" key={relationship.id}><div className="flex flex-wrap items-center justify-between gap-2"><p className="break-words font-semibold text-primary-navy">{relationship.business_identifier}</p><AuditRiskStatusBadge value={relationship.status} /></div><p className="mt-1 text-sm text-text-muted">Corrective Action relationship · Read only</p></li>)}</ul>}
    </AuditRiskSectionCard>
  );
}

function FindingError({ detail = false, error, onRetry }: { detail?: boolean; error: unknown; onRetry: () => void }) {
  const unauthorized = isApiError(error) && error.status === 403;
  const unavailable = detail && isApiError(error) && error.status === 404;
  const malformed = isApiError(error) && error.code === "MALFORMED_RESPONSE";
  const title = unauthorized ? "You are not authorized to view Audit Findings." : unavailable ? "Audit Finding unavailable." : malformed ? "Finding data could not be safely displayed." : "Audit Findings could not be loaded.";
  return <AuditState title={title}><p>{unavailable ? "The Finding does not exist or is outside your authorized scope." : "No partial Finding context has been displayed."}</p>{!unauthorized && !unavailable ? <Button onClick={onRetry} type="button">Try again</Button> : null}</AuditState>;
}
