import { useQuery } from "@tanstack/react-query";
import { Link, useParams, useSearchParams } from "react-router-dom";

import { isApiError } from "../api/errors";
import { routes } from "../app/routePaths";
import { useCan } from "../auth/useCan";
import { Button } from "../ui/components/Button";
import { Surface } from "../ui/components/Surface";
import { auditFindingQueryKeys, getAuditFinding, listAuditFindings } from "./auditRiskApi";
import { AuditState, Context } from "./AuditRiskWorkspacePage";
import { AuditRiskNavigation } from "./AuditRiskNavigation";
import { AuditFindingReadProjection, AuditFindingSeverity, auditFindingSeverities, displayCode, formatDateTime } from "./auditRiskTypes";

export function AuditFindingsPage() {
  const canView = useCan("view_finding");
  const canViewAudit = useCan("view_audit");
  const [searchParams, setSearchParams] = useSearchParams();
  const requestedSeverity = searchParams.get("severity");
  const severity = auditFindingSeverities.includes(requestedSeverity as AuditFindingSeverity)
    ? (requestedSeverity as AuditFindingSeverity)
    : undefined;
  const requestedResolved = searchParams.get("resolved");
  const resolved = requestedResolved === "true" ? true : requestedResolved === "false" ? false : undefined;
  const filters = { ...(severity ? { severity } : {}), ...(resolved === undefined ? {} : { resolved }) };
  const query = useQuery({
    queryKey: auditFindingQueryKeys.list(filters),
    queryFn: () => listAuditFindings(filters),
    enabled: canView,
    retry: false
  });

  if (!canView) return <AuditState title="You are not authorized to view Audit Findings.">Your current session does not include Finding viewing authority.</AuditState>;

  return (
    <section aria-labelledby="audit-findings-heading" className="space-y-4">
      <AuditRiskNavigation />
      <header>
        <p className="text-xs font-semibold uppercase tracking-wide text-primary-blue">Audit &amp; Risk</p>
        <h1 className="mt-2 text-2xl font-semibold text-text-primary" id="audit-findings-heading">Findings</h1>
        <p className="mt-2 max-w-3xl text-sm leading-6 text-text-muted">Review scoped Findings generated by Audit processing. Remediation relationships are reference-only.</p>
      </header>
      <FindingFilters
        resolved={resolved}
        severity={severity}
        onChange={(nextSeverity, nextResolved) => {
          const next = new URLSearchParams();
          if (nextSeverity) next.set("severity", nextSeverity);
          if (nextResolved !== undefined) next.set("resolved", String(nextResolved));
          setSearchParams(next, { replace: true });
        }}
      />
      {query.isLoading ? (
        <AuditState role="status" title="Loading Audit Findings.">Please wait.</AuditState>
      ) : query.isError ? (
        <FindingError error={query.error} onRetry={() => void query.refetch()} />
      ) : !query.data || query.data.findings.length === 0 ? (
        <AuditState title="No Audit Findings are available.">No Findings matched your current filters and authority.</AuditState>
      ) : (
        <FindingList canViewAudit={canViewAudit} findings={query.data.findings} />
      )}
    </section>
  );
}

export function AuditFindingDetailPage() {
  const canView = useCan("view_finding");
  const canViewAudit = useCan("view_audit");
  const { findingId } = useParams();
  const query = useQuery({
    queryKey: auditFindingQueryKeys.detail(findingId ?? ""),
    queryFn: () => getAuditFinding(findingId ?? ""),
    enabled: canView && Boolean(findingId),
    retry: false
  });

  if (!canView) return <AuditState title="You are not authorized to view Audit Findings.">Your current session does not include Finding viewing authority.</AuditState>;
  if (!findingId) return <AuditState title="Audit Finding unavailable.">No Finding identifier was provided.</AuditState>;
  if (query.isLoading) return <AuditState role="status" title="Loading Audit Finding detail.">Please wait.</AuditState>;
  if (query.isError) return <FindingError detail error={query.error} onRetry={() => void query.refetch()} />;
  if (!query.data) return <AuditState title="Audit Finding unavailable.">The Finding service did not return authoritative detail.</AuditState>;

  const finding = query.data;
  return (
    <section aria-labelledby="audit-finding-detail-heading" className="space-y-4">
      <AuditRiskNavigation />
      <Link className="text-sm font-semibold text-primary-blue hover:underline" to={routes.auditFindings}>← Back to Findings</Link>
      <header>
        <p className="text-xs font-semibold uppercase tracking-wide text-primary-blue">Audit &amp; Risk · Finding</p>
        <h1 className="mt-2 text-2xl font-semibold text-text-primary" id="audit-finding-detail-heading">{finding.business_identifier}</h1>
        <p className="mt-2 text-lg font-semibold text-text-primary">{finding.title}</p>
      </header>
      <Surface>
        <dl className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">
          <Context label="Severity" value={displayCode(finding.severity)} />
          <Context label="Resolution" value={finding.is_resolved ? "Resolved" : "Unresolved"} />
          <Context label="Category" value={finding.category} />
          <Context label="Client" value={`${finding.client.name} · ${finding.client.business_identifier}`} />
          <Context label="Facility" value={`${finding.facility.name} · ${finding.facility.business_identifier}`} />
          <div><dt className="text-xs font-semibold uppercase tracking-wide text-text-muted">Parent Audit</dt><dd className="mt-1 text-text-primary">{canViewAudit ? <Link className="text-primary-blue hover:underline" to={routes.auditDetailPath(finding.audit.id)}>{finding.audit.business_identifier}</Link> : finding.audit.business_identifier}</dd></div>
          <Context label="Identified" value={formatDateTime(finding.identified_at)} />
          <Context label="Resolved" value={finding.resolved_at ? formatDateTime(finding.resolved_at) : "Not resolved"} />
        </dl>
      </Surface>
      <Surface>
        <h2 className="text-base font-semibold text-text-primary">Finding narrative</h2>
        <dl className="mt-4 space-y-4">
          <Context label="Description" value={finding.description} />
          <Context label="Recommendation" value={finding.recommendation ?? "No recommendation recorded"} />
        </dl>
      </Surface>
      <RemediationRelationships remediation={finding.remediation} />
    </section>
  );
}

function FindingFilters({ onChange, resolved, severity }: {
  onChange: (severity: AuditFindingSeverity | undefined, resolved: boolean | undefined) => void;
  resolved: boolean | undefined;
  severity: AuditFindingSeverity | undefined;
}) {
  return (
    <Surface>
      <div className="grid gap-4 md:grid-cols-2">
        <label className="block text-sm font-semibold text-text-primary">Severity<select className="mt-1 min-h-10 w-full rounded-component border border-border bg-surface px-3" onChange={(event) => onChange((event.currentTarget.value || undefined) as AuditFindingSeverity | undefined, resolved)} value={severity ?? ""}><option value="">All severities</option>{auditFindingSeverities.map((value) => <option key={value} value={value}>{displayCode(value)}</option>)}</select></label>
        <label className="block text-sm font-semibold text-text-primary">Resolution<select className="mt-1 min-h-10 w-full rounded-component border border-border bg-surface px-3" onChange={(event) => onChange(severity, event.currentTarget.value === "" ? undefined : event.currentTarget.value === "true")} value={resolved === undefined ? "" : String(resolved)}><option value="">All resolution states</option><option value="false">Unresolved</option><option value="true">Resolved</option></select></label>
      </div>
    </Surface>
  );
}

function FindingList({ canViewAudit, findings }: { canViewAudit: boolean; findings: readonly AuditFindingReadProjection[] }) {
  return (
    <Surface>
      <ul aria-label="Scoped Audit Findings" className="divide-y divide-border">
        {findings.map((finding) => (
          <li className="py-4 first:pt-0 last:pb-0" key={finding.id}>
            <article aria-labelledby={`finding-${finding.id}`} className="space-y-2">
              <div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-semibold text-text-primary" id={`finding-${finding.id}`}><Link className="text-primary-blue hover:underline" to={routes.auditFindingDetailPath(finding.id)}>{finding.business_identifier}</Link></h2><p className="text-sm font-semibold text-text-primary">{finding.title}</p><p className="text-sm text-text-muted">{finding.facility.name} · {finding.client.name}</p></div><div className="text-right text-sm"><p className="font-semibold text-text-primary">{displayCode(finding.severity)}</p><p className="text-text-muted">{finding.is_resolved ? "Resolved" : "Unresolved"}</p></div></div>
              <dl className="grid gap-2 text-sm sm:grid-cols-2"><div><dt className="text-xs font-semibold uppercase tracking-wide text-text-muted">Parent Audit</dt><dd className="mt-1 text-text-primary">{canViewAudit ? <Link className="text-primary-blue hover:underline" to={routes.auditDetailPath(finding.audit.id)}>{finding.audit.business_identifier}</Link> : finding.audit.business_identifier}</dd></div><Context label="Identified" value={formatDateTime(finding.identified_at)} /></dl>
            </article>
          </li>
        ))}
      </ul>
    </Surface>
  );
}

function RemediationRelationships({ remediation }: { remediation: AuditFindingReadProjection["remediation"] }) {
  return (
    <Surface>
      <h2 className="text-base font-semibold text-text-primary">Remediation relationships</h2>
      {remediation.length === 0 ? <p className="mt-2 text-sm text-text-muted">No Corrective Action relationships are recorded.</p> : <ul aria-label="Read-only remediation relationships" className="mt-3 space-y-2">{remediation.map((relationship) => <li className="rounded-component border border-border p-3" key={relationship.id}><p className="font-semibold text-text-primary">{relationship.business_identifier}</p><p className="text-sm text-text-muted">Corrective Action · {displayCode(relationship.status)}</p></li>)}</ul>}
    </Surface>
  );
}

function FindingError({ detail = false, error, onRetry }: { detail?: boolean; error: unknown; onRetry: () => void }) {
  const unauthorized = isApiError(error) && error.status === 403;
  const unavailable = detail && isApiError(error) && error.status === 404;
  const malformed = isApiError(error) && error.code === "MALFORMED_RESPONSE";
  const title = unauthorized ? "You are not authorized to view Audit Findings." : unavailable ? "Audit Finding unavailable." : malformed ? "Finding data could not be safely displayed." : "Audit Findings could not be loaded.";
  return <AuditState title={title}><p>{unavailable ? "The Finding does not exist or is outside your authorized scope." : "No partial Finding context has been displayed."}</p>{!unauthorized && !unavailable ? <Button onClick={onRetry} type="button">Try again</Button> : null}</AuditState>;
}
